discourse-moderation-announcement:
  moderation_announcement_enabled:
    default: true
    client: true
  moderation_announcement_deletion_topic_id:
    default: -1
    type: integer
    client: false
